import type { Metadata } from "next";
import { Indie_Flower } from "next/font/google";
import "./globals.css";

const permanentMarker = Indie_Flower({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Verso vivo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      
      <body className={permanentMarker.className}>{children}</body>
    </html>
  );
}
