import type { Metadata } from "next";
import { Gochi_Hand } from "next/font/google";
import "./globals.css";

const gochiHand = Gochi_Hand({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Verso vivo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      
      <body className={gochiHand.className}>{children}</body>
    </html>
  );
}
